import enum
from datetime import datetime
from sqlalchemy import (
    Column, Integer, BigInteger, String, Text, Boolean, DateTime,
    ForeignKey, Enum as SAEnum, Float, JSON, Index
)
from sqlalchemy.orm import DeclarativeBase, relationship
from pgvector.sqlalchemy import Vector

# Embedding dimension — jina-embeddings-v2-base-code produces 768-dim vectors
EMBEDDING_DIM = 768


class Base(DeclarativeBase):
    pass


class IndexStatus(str, enum.Enum):
    pending = "pending"
    indexing = "indexing"
    ready = "ready"
    stale = "stale"
    failed = "failed"


class JobStatus(str, enum.Enum):
    pending = "pending"
    running = "running"
    completed = "completed"
    failed = "failed"


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, autoincrement=True)
    github_id = Column(BigInteger, unique=True, nullable=False, index=True)
    login = Column(String(255), nullable=False)
    name = Column(String(255))
    email = Column(String(255))
    avatar_url = Column(Text)
    github_token_encrypted = Column(Text, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    repos = relationship("Repo", back_populates="user", cascade="all, delete-orphan")
    jobs = relationship("Job", back_populates="user")


class Repo(Base):
    __tablename__ = "repos"

    id = Column(Integer, primary_key=True, autoincrement=True)
    owner = Column(String(255), nullable=False)
    name = Column(String(255), nullable=False)
    url = Column(Text, nullable=False)
    description = Column(Text)
    language = Column(String(100))
    is_private = Column(Boolean, default=False)
    last_commit_sha = Column(String(40))
    indexed_at = Column(DateTime)
    index_status = Column(SAEnum(IndexStatus), default=IndexStatus.pending, nullable=False)
    chunk_count = Column(Integer, default=0)
    file_count = Column(Integer, default=0)
    error_message = Column(Text)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Precomputed file tree — list of relative file paths, stored during ingest
    # Used by wiki sidebar (O(1) lookup vs O(chunks) scan)
    file_tree = Column(JSON, default=list)

    # Extracted dependency names from requirements.txt / package.json / go.mod etc.
    # Used for cross-repo dependency detection in chat
    dependencies = Column(JSON, default=list)

    # AI-generated logical wiki structure — list of {id, title, parent_id, dir_path}
    # Generated by Claude Haiku during ingestion; drives sidebar navigation
    wiki_structure = Column(JSON, default=list)

    user = relationship("User", back_populates="repos")
    chunks = relationship("Chunk", back_populates="repo", cascade="all, delete-orphan")
    wiki_pages = relationship("WikiPage", back_populates="repo", cascade="all, delete-orphan")
    jobs = relationship("Job", back_populates="repo", cascade="all, delete-orphan")

    __table_args__ = (
        Index("ix_repos_user_id", "user_id"),
        Index("ix_repos_owner_name", "owner", "name"),
    )


class WikiGenerationStatus(str, enum.Enum):
    pending = "pending"    # placeholder created, task enqueued
    running = "running"    # task picked up by worker
    ready = "ready"        # content written successfully
    failed = "failed"      # task exhausted retries


class WikiPage(Base):
    __tablename__ = "wiki_pages"

    id = Column(Integer, primary_key=True, autoincrement=True)
    repo_id = Column(Integer, ForeignKey("repos.id", ondelete="CASCADE"), nullable=False)
    path = Column(String(512), nullable=False)  # directory path or "overview"
    title = Column(String(512), nullable=False)
    content_md = Column(Text)
    mermaid_diagram = Column(Text)
    generated_at = Column(DateTime)
    generation_status = Column(
        SAEnum(WikiGenerationStatus),
        default=WikiGenerationStatus.pending,
        nullable=False,
    )

    repo = relationship("Repo", back_populates="wiki_pages")

    __table_args__ = (
        Index("ix_wiki_pages_repo_path", "repo_id", "path", unique=True),
    )


class Chunk(Base):
    __tablename__ = "chunks"

    id = Column(Integer, primary_key=True, autoincrement=True)
    repo_id = Column(Integer, ForeignKey("repos.id", ondelete="CASCADE"), nullable=False)
    file_path = Column(String(1024), nullable=False)
    content = Column(Text, nullable=False)
    embedding = Column(Vector(EMBEDDING_DIM))
    chunk_type = Column(String(50))   # function | class | module | doc
    name = Column(String(512))
    start_line = Column(Integer)
    end_line = Column(Integer)
    language = Column(String(50))
    chunk_metadata = Column("metadata", JSON, default={})

    repo = relationship("Repo", back_populates="chunks")

    __table_args__ = (
        Index("ix_chunks_repo_id", "repo_id"),
        Index("ix_chunks_file_path", "repo_id", "file_path"),
    )


class Job(Base):
    __tablename__ = "jobs"

    id = Column(String(64), primary_key=True)  # Celery task ID
    repo_id = Column(Integer, ForeignKey("repos.id", ondelete="CASCADE"), nullable=False)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    status = Column(SAEnum(JobStatus), default=JobStatus.pending, nullable=False)
    progress_step = Column(String(255))
    progress_pct = Column(Float, default=0.0)
    error = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    repo = relationship("Repo", back_populates="jobs")
    user = relationship("User", back_populates="jobs")
