"""
Wiki page generation using Claude Haiku.
Pages are concept-based (not directory-based): each page is generated by
semantically finding relevant chunks across the whole codebase for that concept.
"""
from typing import List
import anthropic
from core.config import settings

_client: anthropic.Anthropic | None = None


def get_client() -> anthropic.Anthropic:
    global _client
    if _client is None:
        _client = anthropic.Anthropic(api_key=settings.anthropic_api_key)
    return _client


def generate_wiki_page(
    repo_owner: str,
    repo_name: str,
    page_title: str,
    chunks_content: List[dict],
    is_overview: bool = False,
) -> dict:
    """
    Generate a concept-based wiki page from semantically-retrieved chunks.
    Returns {"title": ..., "content_md": ..., "mermaid_diagram": ...}
    """
    client = get_client()

    context_parts = []
    for c in chunks_content[:40]:
        lang = c.get("language", "")
        name = c.get("name", "")
        header = f"### `{c['file_path']}`"
        if name:
            header += f" — `{name}` ({c.get('chunk_type', '')})"
        header += f" lines {c.get('start_line', '?')}-{c.get('end_line', '?')}"
        context_parts.append(f"{header}\n```{lang}\n{c['content']}\n```")
    context = "\n\n".join(context_parts)

    if is_overview:
        prompt = f"""You are a senior software engineer writing internal documentation for `{repo_owner}/{repo_name}`.

Write a comprehensive Overview wiki page in Markdown. This is the landing page for the entire codebase.

RELEVANT CODE:
{context}

Structure the page as:
## Overview
2-3 sentences describing what this repo does and who it's for.

## Architecture
How the system is structured at a high level. Mention the main layers/services.
Include a Mermaid flowchart in a ```mermaid block showing the main components and data flow.

## Key Components
Bullet list of the most important modules/services with one-line descriptions and file paths.

## Tech Stack
What languages, frameworks, and key libraries are used.

## Getting Started
Any setup or entry-point information visible from the code.

Use actual names from the code. Be concise but thorough."""

    else:
        prompt = f"""You are a senior software engineer writing internal documentation for `{repo_owner}/{repo_name}`.

Write a comprehensive wiki article titled **"{page_title}"** in Markdown.

The following code chunks are the most relevant parts of the codebase for this topic:

{context}

Structure the article as:
## Overview
2-3 sentences explaining what this is and why it exists.

## How It Works
Explain the logic, flow, and key design decisions. Walk through the code step by step where helpful.

## Key Components
Important functions, classes, or modules — include the file path and a one-line description for each.

## Data Flow
How data enters, transforms, and exits through this part of the system (skip if not applicable).

## Dependencies
What this component depends on and what depends on it.

Use the actual file paths, function names, and class names from the code above.
Do not fabricate functionality. If context is limited, say so."""

    response = client.messages.create(
        model=settings.haiku_model,
        max_tokens=2500,
        messages=[{"role": "user", "content": prompt}],
    )

    content_md = response.content[0].text

    # Extract mermaid diagram if present
    mermaid_diagram = None
    if "```mermaid" in content_md:
        import re
        match = re.search(r"```mermaid\n(.*?)```", content_md, re.DOTALL)
        if match:
            mermaid_diagram = match.group(1).strip()

    return {
        "title": page_title,
        "content_md": content_md,
        "mermaid_diagram": mermaid_diagram,
    }


def generate_wiki_structure(
    repo_owner: str,
    repo_name: str,
    file_tree: List[str],
) -> List[dict]:
    """
    Generate a logical wiki structure from the file tree.
    Returns a list of pages: [{id, title, parent_id, dir_path}]
    dir_path is a hint for which directory best represents this concept — it does NOT
    need to exactly match a real folder; wiki content is retrieved semantically.
    """
    client = get_client()

    tree_str = "\n".join(file_tree[:200])

    prompt = f"""You are a technical documentation architect. Analyze the file tree of `{repo_owner}/{repo_name}` and generate a logical wiki structure with human-readable page titles — exactly like DeepWiki or Notion organizes documentation.

File tree:
{tree_str}

Generate a JSON array of wiki pages. Each page has:
- "id": a unique slug (e.g. "overview", "authentication", "data-pipeline")
- "title": a human-readable concept title (e.g. "Overview", "Authentication System", "Data Pipeline")
- "parent_id": null for top-level, or the id of the parent page for nested pages
- "dir_path": the directory in the file tree that best represents this concept. Use "overview" for the root/overview page.

Rules:
- Always include an "Overview" page first with id="overview", parent_id=null, dir_path="overview"
- Create 6-15 logical sections based on the actual codebase's concerns
- Group related directories under meaningful parent sections (e.g. "Backend", "Frontend")
- Use clear, concept-level titles (e.g. "Authentication" not "auth/", "Task Queue" not "worker/")
- Max 2 levels of nesting
- dir_path should be the closest matching real directory from the file tree
- Only output valid JSON, no explanation

Example output:
[
  {{"id": "overview", "title": "Overview", "parent_id": null, "dir_path": "overview"}},
  {{"id": "backend", "title": "Backend API", "parent_id": null, "dir_path": "api"}},
  {{"id": "auth", "title": "Authentication", "parent_id": "backend", "dir_path": "api/auth"}},
  {{"id": "database", "title": "Database & Models", "parent_id": null, "dir_path": "db"}}
]"""

    try:
        response = client.messages.create(
            model=settings.haiku_model,
            max_tokens=1500,
            messages=[{"role": "user", "content": prompt}],
        )
        import json, re
        text = response.content[0].text.strip()
        match = re.search(r"\[.*\]", text, re.DOTALL)
        if match:
            text = match.group(0)
        structure = json.loads(text)
        return [
            {
                "id": str(p.get("id", "")),
                "title": str(p.get("title", "")),
                "parent_id": p.get("parent_id"),
                "dir_path": str(p.get("dir_path", "")),
            }
            for p in structure
            if p.get("id") and p.get("title")
        ]
    except Exception:
        return [{"id": "overview", "title": "Overview", "parent_id": None, "dir_path": "overview"}]


def generate_architecture_diagram(
    repo_owner: str,
    repo_name: str,
    file_tree: List[str],
    top_chunks: List[dict],
) -> str:
    """Generate a Mermaid architecture diagram for the repo."""
    client = get_client()

    tree_str = "\n".join(file_tree[:100])
    chunks_str = "\n".join(
        f"- {c['file_path']}: {c.get('name', 'module')} ({c.get('chunk_type', '')})"
        for c in top_chunks[:30]
    )

    prompt = f"""Generate a Mermaid flowchart (graph TD) showing the high-level architecture of `{repo_owner}/{repo_name}`.

File tree:
{tree_str}

Key components:
{chunks_str}

Output ONLY the Mermaid diagram code (no ```mermaid wrapper, just the diagram content starting with "graph TD" or "flowchart TD").
Keep it concise: max 15 nodes, focus on the main data flow and component relationships.
"""

    response = client.messages.create(
        model=settings.haiku_model,
        max_tokens=800,
        messages=[{"role": "user", "content": prompt}],
    )

    return response.content[0].text.strip()
